In [2]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

## Q1

Yes ,There is a difference in the data type between list_ and array_list. 
1. ArrayLists usually contain elements of the same data type. 
2. Lists can often contain elements of different data types within the same list.

In [28]:
print(type(list_))
print(type(array_list))
array_list.dtype

<class 'list'>
<class 'numpy.ndarray'>


dtype('int64')

## Q2

In [23]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [8]:
for j in array_list:
    print(type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Q3

In [9]:
array_list = np.array(object = list_, dtype = int)

In this case, there is a difference in the data type between list_ and array_list due to the explicit specification of the dtype when creating the NumPy array. The elements in list_ are of type Python int, while the elements in array_list are explicitly converted to NumPy int64 or another specified integer data type.



In [29]:
print("Data type of list: ",type(list_[0]))
print("Data type of array_list: ",type(array_list[0]))

Data type of list:  <class 'int'>
Data type of array_list:  <class 'numpy.int64'>


In [30]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [31]:
for j in list_:
    print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


## Q4

In [32]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [34]:
num_array.shape

(2, 3)

In [35]:
num_array.size

6

## Q5

In [38]:
arr = np.zeros((3,3))

In [39]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
arr2 = np.random.randint(0,1,(3,3))

In [42]:
arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Q6

In [44]:
iden_mat = np.eye(5)

In [45]:
iden_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
data1 = np.diag([1,1,1,1,1])

In [47]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])